### ISSUE TITLE
login button not working on ios/iphone

### ISSUE THREAD

**Issue by tasota** [CMU-CREATE-Lab/honeybee-application#13]
seen on 11.2.1 with iphone se

**Comment by tasota** [comment]
@dognotdog I'm not seeing an issue with the login button from the simulator. Providing incorrect username/password does nothing (see #14), but otherwise I login successfully and go to the next page. Do you have any console output to share?

**Comment by dognotdog** [comment]
looks like this was just a missing "secrets" file from the project when doing dev builds.
